@startuml
actor User as user

user -> streamlit : closes the chat page

streamlit -> clips : queries for known facts
streamlit <-- clips

streamlit -> fs : stores user session for later usage
fs --> streamlit

streamlit -> clips : stops engine

@enduml